insert into author (name, id) values ('Адитья Бхаргава', 1)
insert into author (name, id) values ('Тим Рафгарден', 2)
insert into author (name, id) values ('Луридас Панос', 3)
insert into author (name, id) values ('Майкл Солтис', 4)
insert into author (name, id) values ('Джон Клейнберг', 5)

insert into book (author_id, price, title, year, id) values ( 1, 500.0, 'Грокаем алгоритмы', 2017, 1)
insert into book (author_id, price, title, year, id) values ( 2, 1500.0, 'Совершенный алгоритм. Основы', 2019, 2)
insert into book (author_id, price, title, year, id) values ( 2, 999.0, 'Совершенный алгоритм. Графовые алгоритмы и структуры данных', 2019, 3)
insert into book (author_id, price, title, year, id) values ( 3, 1700.0, 'Алгоритмы для начинающих', 2018, 14)
insert into book (author_id, price, title, year, id) values ( 1, 300.0, 'Грокаем алгоритмы', 2021, 5)
insert into book (author_id, price, title, year, id) values ( 4, 500.0, 'Введение в анализ алгоритмов', 2019, 6)
insert into book (author_id, price, title, year, id) values ( 5, 100.0, 'Алгоритмы: разработка и применение', 2016, 7)
insert into book (author_id, price, title, year, id) values ( 1, 1700.0, 'Грокаем алгоритмы', 2022, 8)